[versions]
accompanist = "0.37.3"
activityCompose = "1.12.2"
androidGradlePlugin = "9.0.0"
bugsnagAndroidPerformance = "2.2.0"
colorpickerCompose = "1.1.3"
desugar_jdk_libs = "2.1.5"
shizuku = "13.1.5"
appcompat = "1.7.1"
atomicfu = "0.31.0"
bugsnagAndroid = "6.22.0"
bugsnagGradlePlugin = "1.0.0"
byteBuddyAndroid = "1.18.4"
composeBom = "2026.01.00"
compose-material-icons-core = "1.7.8"
composeintroslider = "a611e4f624"
constraintlayout = "2.2.1"
coreKtx = "1.17.0"
core-remoteviews = "1.1.0"
coroutines = "1.10.2"
gson = "2.13.2"
hiddenapibypass = "6.1"
kotlin = "2.3.0"
lifecycle = "2.10.0"
material = "1.13.0"
msz-progress-indicator = "0.8.0"
patreonsupportersretrieval = "8436bbdbdc"
preferenceKtx = "1.2.1"
recyclerview = "1.4.0"
relinker = "1.4.5"
reorderable = "3.0.0"
seekbarpreference = "963c47439b"
spannedgridlayoutmanager = "999c2fc9f8"
storage = "2.2.0"
taskerpluginlibrary = "0.4.10"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
bugsnag-android = { module = "com.bugsnag:bugsnag-android", version.ref = "bugsnagAndroid" }
bugsnag-android-performance = { module = "com.bugsnag:bugsnag-android-performance", version.ref = "bugsnagAndroidPerformance" }
bugsnag-android-performance-appcompat = { module = "com.bugsnag:bugsnag-android-performance-appcompat", version.ref = "bugsnagAndroidPerformance" }
bugsnag-android-performance-compose = { module = "com.bugsnag:bugsnag-android-performance-compose", version.ref = "bugsnagAndroidPerformance" }
bugsnag-exitinfo = { module = "com.bugsnag:bugsnag-plugin-android-exitinfo", version.ref = "bugsnagAndroid" }
byte-buddy-android = { module = "net.bytebuddy:byte-buddy-android", version.ref = "byteBuddyAndroid" }
colorpicker-compose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpickerCompose" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "compose-material-icons-core" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
composeIntroSlider = { module = "com.github.zacharee:ComposeIntroSlider", version.ref = "composeintroslider" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-remoteviews = { module = "androidx.core:core-remoteviews", version.ref = "core-remoteviews" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
msz-progress-indicator = { module = "com.ehsanmsz:msz-progress-indicator", version.ref = "msz-progress-indicator" }
patreonSupportersRetrieval = { module = "com.github.zacharee:PatreonSupportersRetrieval", version.ref = "patreonsupportersretrieval" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
relinker = { module = "com.getkeepsafe.relinker:relinker", version.ref = "relinker" }
seekBarPreference = { module = "com.github.zacharee:SeekBarPreference", version.ref = "seekbarpreference" }
shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }
spannedGridLayoutManager = { module = "com.github.zacharee:SpannedGridLayoutManager", version.ref = "spannedgridlayoutmanager" }
storage = { module = "com.anggrayudi:storage", version.ref = "storage" }
taskerpluginlibrary = { module = "com.joaomgcd:taskerpluginlibrary", version.ref = "taskerpluginlibrary" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
bugsnag = { id = "com.bugsnag.gradle", version.ref = "bugsnagGradlePlugin" }
kotlin-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
