[versions]
accompanist = "0.36.0"
activityCompose = "1.9.2"
androidGradlePlugin = "8.5.2"
appcompat = "1.7.0"
atomicfu = "0.25.0"
bugsnagAndroid = "6.7.0"
bugsnagGradlePlugin = "0.1.0"
byteBuddyAndroid = "1.15.1"
collapsiblepreferencecategory = "2f53f2d367"
colorpicker = "c300c66e93"
composeBom = "2024.09.01"
composeintroslider = "a611e4f624"
composeSpinkit = "1.0.4"
constraintlayout = "2.2.0-beta01"
coreKtx = "1.13.1"
coroutines = "1.9.0"
gson = "2.11.0"
hiddenapibypass = "4.3"
kotlin = "2.1.0-Beta1"
lifecycle = "2.8.5"
material = "1.13.0-alpha06"
patreonsupportersretrieval = "8436bbdbdc"
preferenceKtx = "1.2.1"
recyclerview = "1.3.2"
relinker = "1.4.5"
seekbarpreference = "963c47439b"
spannedgridlayoutmanager = "0c56d2019a"
taskerpluginlibrary = "0.4.10"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-themeadapter-material = { module = "com.google.accompanist:accompanist-themeadapter-material", version.ref = "accompanist" }
accompanist-themeadapter-material3 = { module = "com.google.accompanist:accompanist-themeadapter-material3", version.ref = "accompanist" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
bugsnag-android = { module = "com.bugsnag:bugsnag-android", version.ref = "bugsnagAndroid" }
byte-buddy-android = { module = "net.bytebuddy:byte-buddy-android", version.ref = "byteBuddyAndroid" }
collapsiblePreferenceCategory = { module = "com.github.zacharee:CollapsiblePreferenceCategory", version.ref = "collapsiblepreferencecategory" }
colorpicker = { module = "com.github.zacharee:colorpicker", version.ref = "colorpicker" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-spinkit = { module = "com.github.OCNYang:Compose-SpinKit", version.ref = "composeSpinkit" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
composeIntroSlider = { module = "com.github.zacharee:ComposeIntroSlider", version.ref = "composeintroslider" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
patreonSupportersRetrieval = { module = "com.github.zacharee:PatreonSupportersRetrieval", version.ref = "patreonsupportersretrieval" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
relinker = { module = "com.getkeepsafe.relinker:relinker", version.ref = "relinker" }
seekBarPreference = { module = "com.github.zacharee:SeekBarPreference", version.ref = "seekbarpreference" }
spannedGridLayoutManager = { module = "com.github.zacharee:SpannedGridLayoutManager", version.ref = "spannedgridlayoutmanager" }
taskerpluginlibrary = { module = "com.joaomgcd:taskerpluginlibrary", version.ref = "taskerpluginlibrary" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
bugsnag = { id = "com.bugsnag.gradle", version.ref = "bugsnagGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }